version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 8
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 8
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
  - package-ecosystem: "rust-toolchain"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
