---
name: bibdata
services:
  bibdata_test_solr:
    type: solr:custom
    overrides:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.1
      command: server/scripts/lando-start.sh
    portforward: true
    core: bibdata-core-test
    config:
      dir: "solr/conf"
  bibdata_development_solr:
    type: solr:custom
    overrides:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.1
      command: server/scripts/lando-start.sh
    portforward: true
    core: bibdata-core-development
    config:
      dir: "solr/conf"
  bibdata_database:
    type: postgres:13
    portforward: true
  bibdata_redis:
    type: redis:7
    portforward: true
proxy:
  bibdata_test_solr:
    - bibdata.test.solr.lndo.site:8983
  bibdata_development_solr:
    - bibdata.dev.solr.lndo.site:8983
