inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'marc_to_solr/translation_maps/location_display.rb'
    - 'marc_to_solr/translation_maps/locations.rb'
    - 'marc_to_solr/translation_maps/holding_library.rb'

Style/AsciiComments:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/FormatString:
  Exclude:
    - 'marc_to_solr/lib/princeton_marc.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'
    - 'marc_to_solr/**/*'
    - 'app/**/*'

Lint/SuppressedException:
  Exclude:
    - 'lib/tasks/spec.rake'
    - 'marc_to_solr/lib/location_extract.rb'

Metrics/ModuleLength:
  Exclude:
    - 'marc_to_solr/lib/process_holdings_helpers.rb'

Naming/VariableNumber:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/db/seeds_spec.rb'
    - 'spec/marc_to_solr/**/*'
    - 'spec/system/location_views_associated_links_spec.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'marc_to_solr/lib/princeton_marc.rb'

Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/delivery_location.rb'
    - 'app/models/holding_location.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/*'

Rails/ApplicationRecord:
  Exclude:
    - 'app/models/*'

Security/Open:
  Enabled: true
