inherit_from: .rubocop_todo.yml

require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/models/jsonld_record_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'lib/tasks/spec.rake'
    - 'marc_to_solr/lib/location_extract.rb'

RSpec/ExampleLength:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'marc_to_solr/lib/princeton_marc.rb'
