language: ruby
rvm:
  - jruby-9.0.4.0 # JRuby most recent
# uncomment this line if your project needs to run something other than `rake`:
jdk:
  - oraclejdk8
script: bundle exec rspec spec

branches:
  only:
    - development
notifications:
  email:
    recipients:
      - "tampakis@princeton.edu"
      - "jstroop@princeton.edu"
      - "kr2@princeton.edu"
    on_success: "change"
    on_failure: "always"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"