source 'https://rubygems.org'

gem 'bixby', '~> 1.0'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'capistrano-rails', '~> 1.1.1'
gem 'capybara'
gem 'ddtrace'
gem 'devise', '~> 4.3'
gem 'faraday', '~> 0.13'
gem 'faraday_middleware', '~> 0.12'
gem 'ffi', '>= 1.9.25'
gem 'friendly_id', '~> 5.1.0'
gem 'gyoku', '~> 1.0'
gem 'high_voltage', '~> 3.0'
gem 'honeybadger', '~> 3.1'
gem 'iso-639'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'library_stdnums'
gem 'lightly'
gem 'locations', github: "pulibrary/locations", tag: 'v1.2.0'
gem 'lograge'
gem 'logstash-event'
gem 'loofah', '>= 2.2.3'
gem 'loops', github: 'kovyrin/loops', branch: 'master'
gem 'marc', '~> 1.0'
gem 'marc_cleanup', github: "pulibrary/marc_cleanup", tag: 'v0.7.0'
gem 'multi_json', '~> 1.10.1'
gem 'mysql2'
gem 'net-sftp', '~> 2.1', '>= 2.1.2'
gem 'oj'
gem 'omniauth-cas'
gem 'orangetheses', github: 'pulibrary/orangetheses', tag: 'v1.0'
gem 'poltergeist'
gem "rack", ">= 2.0.6"
gem 'rack-conneg', '~> 0.1.5'
gem 'rails', '~> 5.1'
gem 'responders', '~> 2.3'
gem 'rsolr'
gem 'rspec-rails', '~> 3.8'
gem 'rubocop', '~> 0.52.1'
gem 'rubocop-rspec', '~> 1.22'
gem 'ruby-oci8', '~> 2.2.1' unless ENV['CI']
gem 'rubyzip', '>= 1.2.2'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sidekiq'
gem 'stomp'
gem 'stringex', github: "pulibrary/stringex", tag: 'vpton.2.5.2.2'
gem 'traject', '2.3.1'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'voyager_helpers', github: "pulibrary/voyager_helpers", branch: 'master'
gem 'whenever', "~> 0.10"
gem 'yaml_db', '~> 0.6.0'

group :development do
  gem 'spring'
end

group :development, :test do
  # bundler and rake come in from the voyager_helpers gemspec
  gem 'coveralls', '0.8.21'
  gem "factory_bot_rails", "~> 4.0"
  gem 'pry-byebug', '~> 3.0'
  gem 'rails-controller-testing'
  gem 'rerun', '~> 0.10.0'
  gem 'simplecov', '0.14.1'
  gem 'webmock'
end
