source 'https://rubygems.org'

gem 'alma', github: 'tulibraries/alma_rb', branch: 'main'
gem 'aws-sdk-s3'
gem 'aws-sdk-sqs'
gem 'bixby', '~> 2.0'
gem 'bootstrap-sass', '~> 3.4.1'
gem 'capistrano-rails', '~> 1.1.1'
gem 'capistrano-rails-console', require: false
gem 'capybara'
gem 'ddtrace'
gem 'devise', '~> 4.7.1'
gem 'faraday', '~> 1.0.1'
gem 'faraday_middleware', '~> 1.0.0'
gem 'ffi', '>= 1.9.25'
gem 'friendly_id', '~> 5.1.0'
gem 'gyoku', '~> 1.0'
gem 'high_voltage', '~> 3.0'
gem 'honeybadger', '~> 3.1'
gem 'iso-639'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'lcsort'
gem 'library_stdnums'
gem 'lightly'
gem 'locations', github: "pulibrary/locations", tag: 'v1.3.0'
gem 'lograge'
gem 'logstash-event'
gem 'loofah', '>= 2.2.3'
gem 'loops', github: 'kovyrin/loops', branch: 'master'
gem 'marc', '~> 1.0'
gem 'marc_cleanup', github: "pulibrary/marc_cleanup", tag: 'v0.7.0'
gem 'multi_json', '~> 1.10.1'
gem 'net-ldap'
gem 'net-sftp', '~> 2.1', '>= 2.1.2'
gem 'oj'
gem 'omniauth-cas'
gem 'orangetheses', github: 'pulibrary/orangetheses', tag: 'v1.1'
gem 'pg'
gem "rack", ">= 2.0.6"
gem 'rack-conneg', '~> 0.1.5'
gem 'rails', '~> 5.2.4'
gem 'responders', '~> 2.3'
gem 'rest-client'
gem 'rsolr'
gem 'rspec-rails', '~> 3.8'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'rubyXL'
gem 'rubyzip', '>= 1.2.2'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'selenium-webdriver'
gem 'sidekiq'
gem 'stomp'
gem 'stringex', github: "pulibrary/stringex", tag: 'vpton.2.5.2.2'
gem 'traject', '2.3.1'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'whenever', "~> 0.10"
gem 'yaml_db', '~> 0.7.0'
gem 'yard'

group :development do
  gem 'spring'
end

group :development, :test do
  # bundler and rake come in from the voyager_helpers gemspec
  gem 'coveralls', '0.8.21'
  gem "dotenv-rails"
  gem "factory_bot_rails", "~> 4.0"
  gem 'pry-byebug', '~> 3.0'
  gem 'pry-rails'
  gem 'puma'
  gem 'rails-controller-testing'
  gem 'rerun', '~> 0.10.0'
  gem 'simplecov', '0.14.1'
  gem 'solargraph'
  gem 'solr_wrapper'
  gem "webdrivers"
  gem 'webmock'
end
