# frozen_string_literal: true

source 'https://rubygems.org'

gem "aws-sdk-lambda"
gem "aws-sdk-secretsmanager"
gem "aws-sdk-sqs"
gem "datadog-lambda"
gem "ddtrace"

gem 'pry-byebug', '~> 3.0'
gem 'rspec'
