# frozen_string_literal: true

source 'https://rubygems.org'

gem "aws-sdk-secretsmanager"

group :development do
  gem "aws-sdk-lambda"
  gem "aws-sdk-sqs"
  gem "ddtrace"
  gem "datadog-lambda"
  gem "nokogiri"
end

group :test do
  gem 'rspec'
end