source 'https://rubygems.org'
ruby '2.3.0', :engine => 'jruby', :engine_version => '9.1.2.0'

# Traject Marc to Solr
gem 'traject', '~> 2.0'

gem 'stringex', :git => 'https://github.com/pulibrary/stringex.git', :tag => 'vpton.2.5.2.2'

gem 'rsolr'

gem 'faraday'

gem 'library_stdnums'

group :development do
	# rspec
	gem 'rspec', '~> 3.2'
end