source 'https://rubygems.org'
# ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.25'
ruby '1.9.3', :engine => 'jruby', :engine_version => '1.7.25'

# Traject Marc to Solr
gem 'traject', '~> 2.0'

gem 'stringex', :git => 'https://github.com/pulibrary/stringex.git', :tag => 'vpton.2.5.2.2'

gem 'rsolr'

gem 'faraday'

gem 'library_stdnums'

group :development do
	# rspec
	gem 'rspec', '~> 3.2'
end
