default: &default
  netids: <%= ENV['BIBDATA_ADMIN_NETIDS'] || '' %>

development:
  <<: *default

test:
  <<: *default
  netids: admin123

production:
  <<: *default

qa:
  <<: *default

staging:
  <<: *default
