---
default: &default
  server: <%= ENV["DSPACE_URL"] || "https://theses-dissertations.princeton.edu/server/api" %>
  legacy_server: <%= ENV["LEGACY_DSPACE_URL"] || "https://dataspace-dev.princeton.edu/rest" %>
  community: 88435/dsp019c67wm88m
  rest_limit: 100
  retry_limit: 5
  filepath: <%= ENV["FILEPATH"] || "/tmp/theses.json" %>
  temp_filepath: <%= ENV["TEMP_FILEPATH"] || "/tmp/temp_theses.json" %>
  temp_legacy_filepath: <%= ENV["TEMP_LEGACY_FILEPATH"] || "/tmp/temp_legacy_theses.json" %>

development: *default

test: *default

staging:
  <<: *default
  server: <%= ENV["LEGACY_DSPACE_URL"] || "https://dataspace-staging.princeton.edu/rest" %>

production:
  <<: *default
  server: <%= ENV["LEGACY_DSPACE_URL"] || "https://dataspace.princeton.edu/rest" %>
