// This file is automatically generated.  Please do not edit it directly,
// instead run `bundle exec rake languages:iso639_5:refresh_list`
use super::Language;
pub fn from_iso_639_5_code(code: &str) -> Option<Language> {
    match code {
        "aav" => Some(Language {
            english_name: "Austro-Asiatic languages",
            two_letter_code: None,
        }),
        "afa" => Some(Language {
            english_name: "Afro-Asiatic languages",
            two_letter_code: None,
        }),
        "alg" => Some(Language {
            english_name: "Algonquian languages",
            two_letter_code: None,
        }),
        "alv" => Some(Language {
            english_name: "Atlantic-Congo languages",
            two_letter_code: None,
        }),
        "apa" => Some(Language {
            english_name: "Apache languages",
            two_letter_code: None,
        }),
        "aqa" => Some(Language {
            english_name: "Alacalufan languages",
            two_letter_code: None,
        }),
        "aql" => Some(Language {
            english_name: "Algic languages",
            two_letter_code: None,
        }),
        "art" => Some(Language {
            english_name: "Artificial languages",
            two_letter_code: None,
        }),
        "ath" => Some(Language {
            english_name: "Athapascan languages",
            two_letter_code: None,
        }),
        "auf" => Some(Language {
            english_name: "Arauan languages",
            two_letter_code: None,
        }),
        "aus" => Some(Language {
            english_name: "Australian languages",
            two_letter_code: None,
        }),
        "awd" => Some(Language {
            english_name: "Arawakan languages",
            two_letter_code: None,
        }),
        "azc" => Some(Language {
            english_name: "Uto-Aztecan languages",
            two_letter_code: None,
        }),
        "bad" => Some(Language {
            english_name: "Banda languages",
            two_letter_code: None,
        }),
        "bai" => Some(Language {
            english_name: "Bamileke languages",
            two_letter_code: None,
        }),
        "bat" => Some(Language {
            english_name: "Baltic languages",
            two_letter_code: None,
        }),
        "ber" => Some(Language {
            english_name: "Berber languages",
            two_letter_code: None,
        }),
        "bih" => Some(Language {
            english_name: "Bihari languages",
            two_letter_code: None,
        }),
        "bnt" => Some(Language {
            english_name: "Bantu languages",
            two_letter_code: None,
        }),
        "btk" => Some(Language {
            english_name: "Batak languages",
            two_letter_code: None,
        }),
        "cai" => Some(Language {
            english_name: "Central American Indian languages",
            two_letter_code: None,
        }),
        "cau" => Some(Language {
            english_name: "Caucasian languages",
            two_letter_code: None,
        }),
        "cba" => Some(Language {
            english_name: "Chibchan languages",
            two_letter_code: None,
        }),
        "ccn" => Some(Language {
            english_name: "North Caucasian languages",
            two_letter_code: None,
        }),
        "ccs" => Some(Language {
            english_name: "South Caucasian languages",
            two_letter_code: None,
        }),
        "cdc" => Some(Language {
            english_name: "Chadic languages",
            two_letter_code: None,
        }),
        "cdd" => Some(Language {
            english_name: "Caddoan languages",
            two_letter_code: None,
        }),
        "cel" => Some(Language {
            english_name: "Celtic languages",
            two_letter_code: None,
        }),
        "cmc" => Some(Language {
            english_name: "Chamic languages",
            two_letter_code: None,
        }),
        "cpe" => Some(Language {
            english_name: "Creoles and pidgins, English‑based",
            two_letter_code: None,
        }),
        "cpf" => Some(Language {
            english_name: "Creoles and pidgins, French‑based",
            two_letter_code: None,
        }),
        "cpp" => Some(Language {
            english_name: "Creoles and pidgins, Portuguese-based",
            two_letter_code: None,
        }),
        "crp" => Some(Language {
            english_name: "Creoles and pidgins",
            two_letter_code: None,
        }),
        "csu" => Some(Language {
            english_name: "Central Sudanic languages",
            two_letter_code: None,
        }),
        "cus" => Some(Language {
            english_name: "Cushitic languages",
            two_letter_code: None,
        }),
        "day" => Some(Language {
            english_name: "Land Dayak languages",
            two_letter_code: None,
        }),
        "dmn" => Some(Language {
            english_name: "Mande languages",
            two_letter_code: None,
        }),
        "dra" => Some(Language {
            english_name: "Dravidian languages",
            two_letter_code: None,
        }),
        "egx" => Some(Language {
            english_name: "Egyptian languages",
            two_letter_code: None,
        }),
        "esx" => Some(Language {
            english_name: "Eskimo-Aleut languages",
            two_letter_code: None,
        }),
        "euq" => Some(Language {
            english_name: "Basque (family)",
            two_letter_code: None,
        }),
        "fiu" => Some(Language {
            english_name: "Finno-Ugrian languages",
            two_letter_code: None,
        }),
        "fox" => Some(Language {
            english_name: "Formosan languages",
            two_letter_code: None,
        }),
        "gem" => Some(Language {
            english_name: "Germanic languages",
            two_letter_code: None,
        }),
        "gme" => Some(Language {
            english_name: "East Germanic languages",
            two_letter_code: None,
        }),
        "gmq" => Some(Language {
            english_name: "North Germanic languages",
            two_letter_code: None,
        }),
        "gmw" => Some(Language {
            english_name: "West Germanic languages",
            two_letter_code: None,
        }),
        "grk" => Some(Language {
            english_name: "Greek languages",
            two_letter_code: None,
        }),
        "hmx" => Some(Language {
            english_name: "Hmong-Mien languages",
            two_letter_code: None,
        }),
        "hok" => Some(Language {
            english_name: "Hokan languages",
            two_letter_code: None,
        }),
        "hyx" => Some(Language {
            english_name: "Armenian (family)",
            two_letter_code: None,
        }),
        "iir" => Some(Language {
            english_name: "Indo-Iranian languages",
            two_letter_code: None,
        }),
        "ijo" => Some(Language {
            english_name: "Ijo languages",
            two_letter_code: None,
        }),
        "inc" => Some(Language {
            english_name: "Indic languages",
            two_letter_code: None,
        }),
        "ine" => Some(Language {
            english_name: "Indo-European languages",
            two_letter_code: None,
        }),
        "ira" => Some(Language {
            english_name: "Iranian languages",
            two_letter_code: None,
        }),
        "iro" => Some(Language {
            english_name: "Iroquoian languages",
            two_letter_code: None,
        }),
        "itc" => Some(Language {
            english_name: "Italic languages",
            two_letter_code: None,
        }),
        "jpx" => Some(Language {
            english_name: "Japanese (family)",
            two_letter_code: None,
        }),
        "kar" => Some(Language {
            english_name: "Karen languages",
            two_letter_code: None,
        }),
        "kdo" => Some(Language {
            english_name: "Kordofanian languages",
            two_letter_code: None,
        }),
        "khi" => Some(Language {
            english_name: "Khoisan languages",
            two_letter_code: None,
        }),
        "kro" => Some(Language {
            english_name: "Kru languages",
            two_letter_code: None,
        }),
        "map" => Some(Language {
            english_name: "Austronesian languages",
            two_letter_code: None,
        }),
        "mkh" => Some(Language {
            english_name: "Mon-Khmer languages",
            two_letter_code: None,
        }),
        "mno" => Some(Language {
            english_name: "Manobo languages",
            two_letter_code: None,
        }),
        "mun" => Some(Language {
            english_name: "Munda languages",
            two_letter_code: None,
        }),
        "myn" => Some(Language {
            english_name: "Mayan languages",
            two_letter_code: None,
        }),
        "nah" => Some(Language {
            english_name: "Nahuatl languages",
            two_letter_code: None,
        }),
        "nai" => Some(Language {
            english_name: "North American Indian languages",
            two_letter_code: None,
        }),
        "ngf" => Some(Language {
            english_name: "Trans-New Guinea languages",
            two_letter_code: None,
        }),
        "nic" => Some(Language {
            english_name: "Niger-Kordofanian languages",
            two_letter_code: None,
        }),
        "nub" => Some(Language {
            english_name: "Nubian languages",
            two_letter_code: None,
        }),
        "omq" => Some(Language {
            english_name: "Oto-Manguean languages",
            two_letter_code: None,
        }),
        "omv" => Some(Language {
            english_name: "Omotic languages",
            two_letter_code: None,
        }),
        "oto" => Some(Language {
            english_name: "Otomian languages",
            two_letter_code: None,
        }),
        "paa" => Some(Language {
            english_name: "Papuan languages",
            two_letter_code: None,
        }),
        "phi" => Some(Language {
            english_name: "Philippine languages",
            two_letter_code: None,
        }),
        "plf" => Some(Language {
            english_name: "Central Malayo-Polynesian languages",
            two_letter_code: None,
        }),
        "poz" => Some(Language {
            english_name: "Malayo-Polynesian languages",
            two_letter_code: None,
        }),
        "pqe" => Some(Language {
            english_name: "Eastern Malayo-Polynesian languages",
            two_letter_code: None,
        }),
        "pqw" => Some(Language {
            english_name: "Western Malayo-Polynesian languages",
            two_letter_code: None,
        }),
        "pra" => Some(Language {
            english_name: "Prakrit languages",
            two_letter_code: None,
        }),
        "qwe" => Some(Language {
            english_name: "Quechuan (family)",
            two_letter_code: None,
        }),
        "roa" => Some(Language {
            english_name: "Romance languages",
            two_letter_code: None,
        }),
        "sai" => Some(Language {
            english_name: "South American Indian languages",
            two_letter_code: None,
        }),
        "sal" => Some(Language {
            english_name: "Salishan languages",
            two_letter_code: None,
        }),
        "sdv" => Some(Language {
            english_name: "Eastern Sudanic languages",
            two_letter_code: None,
        }),
        "sem" => Some(Language {
            english_name: "Semitic languages",
            two_letter_code: None,
        }),
        "sgn" => Some(Language {
            english_name: "sign languages",
            two_letter_code: None,
        }),
        "sio" => Some(Language {
            english_name: "Siouan languages",
            two_letter_code: None,
        }),
        "sit" => Some(Language {
            english_name: "Sino-Tibetan languages",
            two_letter_code: None,
        }),
        "sla" => Some(Language {
            english_name: "Slavic languages",
            two_letter_code: None,
        }),
        "smi" => Some(Language {
            english_name: "Sami languages",
            two_letter_code: None,
        }),
        "son" => Some(Language {
            english_name: "Songhai languages",
            two_letter_code: None,
        }),
        "sqj" => Some(Language {
            english_name: "Albanian languages",
            two_letter_code: None,
        }),
        "ssa" => Some(Language {
            english_name: "Nilo-Saharan languages",
            two_letter_code: None,
        }),
        "syd" => Some(Language {
            english_name: "Samoyedic languages",
            two_letter_code: None,
        }),
        "tai" => Some(Language {
            english_name: "Tai languages",
            two_letter_code: None,
        }),
        "tbq" => Some(Language {
            english_name: "Tibeto-Burman languages",
            two_letter_code: None,
        }),
        "trk" => Some(Language {
            english_name: "Turkic languages",
            two_letter_code: None,
        }),
        "tup" => Some(Language {
            english_name: "Tupi languages",
            two_letter_code: None,
        }),
        "tut" => Some(Language {
            english_name: "Altaic languages",
            two_letter_code: None,
        }),
        "tuw" => Some(Language {
            english_name: "Tungus languages",
            two_letter_code: None,
        }),
        "urj" => Some(Language {
            english_name: "Uralic languages",
            two_letter_code: None,
        }),
        "wak" => Some(Language {
            english_name: "Wakashan languages",
            two_letter_code: None,
        }),
        "wen" => Some(Language {
            english_name: "Sorbian languages",
            two_letter_code: None,
        }),
        "xgn" => Some(Language {
            english_name: "Mongolian languages",
            two_letter_code: None,
        }),
        "xnd" => Some(Language {
            english_name: "Na-Dene languages",
            two_letter_code: None,
        }),
        "ypk" => Some(Language {
            english_name: "Yupik languages",
            two_letter_code: None,
        }),
        "zhx" => Some(Language {
            english_name: "Chinese (family)",
            two_letter_code: None,
        }),
        "zle" => Some(Language {
            english_name: "East Slavic languages",
            two_letter_code: None,
        }),
        "zls" => Some(Language {
            english_name: "South Slavic languages",
            two_letter_code: None,
        }),
        "zlw" => Some(Language {
            english_name: "West Slavic languages",
            two_letter_code: None,
        }),
        "znd" => Some(Language {
            english_name: "Zande languages",
            two_letter_code: None,
        }),
        _ => None,
    }
}
