// This file is automatically generated.  Please do not edit it directly,
// instead run `bundle exec rake languages:iso639_2b:refresh_list`
use super::Language;
pub fn from_iso_639b_code(code: &str) -> Option<Language> {
    match code {
        "aar" => Some(Language {
            english_name: "Afar",
            two_letter_code: Some("aa"),
        }),
        "abk" => Some(Language {
            english_name: "Abkhazian",
            two_letter_code: Some("ab"),
        }),
        "ace" => Some(Language {
            english_name: "Achinese",
            two_letter_code: None,
        }),
        "ach" => Some(Language {
            english_name: "Acoli",
            two_letter_code: None,
        }),
        "ada" => Some(Language {
            english_name: "Adangme",
            two_letter_code: None,
        }),
        "ady" => Some(Language {
            english_name: "Adyghe",
            two_letter_code: None,
        }),
        "afa" => Some(Language {
            english_name: "Afro-Asiatic languages",
            two_letter_code: None,
        }),
        "afh" => Some(Language {
            english_name: "Afrihili",
            two_letter_code: None,
        }),
        "afr" => Some(Language {
            english_name: "Afrikaans",
            two_letter_code: Some("af"),
        }),
        "ain" => Some(Language {
            english_name: "Ainu",
            two_letter_code: None,
        }),
        "aka" => Some(Language {
            english_name: "Akan",
            two_letter_code: Some("ak"),
        }),
        "akk" => Some(Language {
            english_name: "Akkadian",
            two_letter_code: None,
        }),
        "alb" => Some(Language {
            english_name: "Albanian",
            two_letter_code: Some("sq"),
        }),
        "ale" => Some(Language {
            english_name: "Aleut",
            two_letter_code: None,
        }),
        "alg" => Some(Language {
            english_name: "Algonquian languages",
            two_letter_code: None,
        }),
        "alt" => Some(Language {
            english_name: "Southern Altai",
            two_letter_code: None,
        }),
        "amh" => Some(Language {
            english_name: "Amharic",
            two_letter_code: Some("am"),
        }),
        "ang" => Some(Language {
            english_name: "English, Old (ca.450-1100)",
            two_letter_code: None,
        }),
        "anp" => Some(Language {
            english_name: "Angika",
            two_letter_code: None,
        }),
        "apa" => Some(Language {
            english_name: "Apache languages",
            two_letter_code: None,
        }),
        "ara" => Some(Language {
            english_name: "Arabic",
            two_letter_code: Some("ar"),
        }),
        "arc" => Some(Language {
            english_name: "Official Aramaic (700-300 BCE)",
            two_letter_code: None,
        }),
        "arg" => Some(Language {
            english_name: "Aragonese",
            two_letter_code: Some("an"),
        }),
        "arm" => Some(Language {
            english_name: "Armenian",
            two_letter_code: Some("hy"),
        }),
        "arn" => Some(Language {
            english_name: "Mapudungun",
            two_letter_code: None,
        }),
        "arp" => Some(Language {
            english_name: "Arapaho",
            two_letter_code: None,
        }),
        "art" => Some(Language {
            english_name: "Artificial languages",
            two_letter_code: None,
        }),
        "arw" => Some(Language {
            english_name: "Arawak",
            two_letter_code: None,
        }),
        "asm" => Some(Language {
            english_name: "Assamese",
            two_letter_code: Some("as"),
        }),
        "ast" => Some(Language {
            english_name: "Asturian",
            two_letter_code: None,
        }),
        "ath" => Some(Language {
            english_name: "Athapascan languages",
            two_letter_code: None,
        }),
        "aus" => Some(Language {
            english_name: "Australian languages",
            two_letter_code: None,
        }),
        "ava" => Some(Language {
            english_name: "Avaric",
            two_letter_code: Some("av"),
        }),
        "ave" => Some(Language {
            english_name: "Avestan",
            two_letter_code: Some("ae"),
        }),
        "awa" => Some(Language {
            english_name: "Awadhi",
            two_letter_code: None,
        }),
        "aym" => Some(Language {
            english_name: "Aymara",
            two_letter_code: Some("ay"),
        }),
        "aze" => Some(Language {
            english_name: "Azerbaijani",
            two_letter_code: Some("az"),
        }),
        "bad" => Some(Language {
            english_name: "Banda languages",
            two_letter_code: None,
        }),
        "bai" => Some(Language {
            english_name: "Bamileke languages",
            two_letter_code: None,
        }),
        "bak" => Some(Language {
            english_name: "Bashkir",
            two_letter_code: Some("ba"),
        }),
        "bal" => Some(Language {
            english_name: "Baluchi",
            two_letter_code: None,
        }),
        "bam" => Some(Language {
            english_name: "Bambara",
            two_letter_code: Some("bm"),
        }),
        "ban" => Some(Language {
            english_name: "Balinese",
            two_letter_code: None,
        }),
        "baq" => Some(Language {
            english_name: "Basque",
            two_letter_code: Some("eu"),
        }),
        "bas" => Some(Language {
            english_name: "Basa",
            two_letter_code: None,
        }),
        "bat" => Some(Language {
            english_name: "Baltic languages",
            two_letter_code: None,
        }),
        "bej" => Some(Language {
            english_name: "Beja",
            two_letter_code: None,
        }),
        "bel" => Some(Language {
            english_name: "Belarusian",
            two_letter_code: Some("be"),
        }),
        "bem" => Some(Language {
            english_name: "Bemba",
            two_letter_code: None,
        }),
        "ben" => Some(Language {
            english_name: "Bengali",
            two_letter_code: Some("bn"),
        }),
        "ber" => Some(Language {
            english_name: "Berber languages",
            two_letter_code: None,
        }),
        "bho" => Some(Language {
            english_name: "Bhojpuri",
            two_letter_code: None,
        }),
        "bih" => Some(Language {
            english_name: "Bihari languages",
            two_letter_code: None,
        }),
        "bik" => Some(Language {
            english_name: "Bikol",
            two_letter_code: None,
        }),
        "bin" => Some(Language {
            english_name: "Bini",
            two_letter_code: None,
        }),
        "bis" => Some(Language {
            english_name: "Bislama",
            two_letter_code: Some("bi"),
        }),
        "bla" => Some(Language {
            english_name: "Siksika",
            two_letter_code: None,
        }),
        "bnt" => Some(Language {
            english_name: "Bantu languages",
            two_letter_code: None,
        }),
        "bos" => Some(Language {
            english_name: "Bosnian",
            two_letter_code: Some("bs"),
        }),
        "bra" => Some(Language {
            english_name: "Braj",
            two_letter_code: None,
        }),
        "bre" => Some(Language {
            english_name: "Breton",
            two_letter_code: Some("br"),
        }),
        "btk" => Some(Language {
            english_name: "Batak languages",
            two_letter_code: None,
        }),
        "bua" => Some(Language {
            english_name: "Buriat",
            two_letter_code: None,
        }),
        "bug" => Some(Language {
            english_name: "Buginese",
            two_letter_code: None,
        }),
        "bul" => Some(Language {
            english_name: "Bulgarian",
            two_letter_code: Some("bg"),
        }),
        "bur" => Some(Language {
            english_name: "Burmese",
            two_letter_code: Some("my"),
        }),
        "byn" => Some(Language {
            english_name: "Blin",
            two_letter_code: None,
        }),
        "cad" => Some(Language {
            english_name: "Caddo",
            two_letter_code: None,
        }),
        "cai" => Some(Language {
            english_name: "Central American Indian languages",
            two_letter_code: None,
        }),
        "car" => Some(Language {
            english_name: "Galibi Carib",
            two_letter_code: None,
        }),
        "cat" => Some(Language {
            english_name: "Catalan",
            two_letter_code: Some("ca"),
        }),
        "cau" => Some(Language {
            english_name: "Caucasian languages",
            two_letter_code: None,
        }),
        "ceb" => Some(Language {
            english_name: "Cebuano",
            two_letter_code: None,
        }),
        "cel" => Some(Language {
            english_name: "Celtic languages",
            two_letter_code: None,
        }),
        "cha" => Some(Language {
            english_name: "Chamorro",
            two_letter_code: Some("ch"),
        }),
        "chb" => Some(Language {
            english_name: "Chibcha",
            two_letter_code: None,
        }),
        "che" => Some(Language {
            english_name: "Chechen",
            two_letter_code: Some("ce"),
        }),
        "chg" => Some(Language {
            english_name: "Chagatai",
            two_letter_code: None,
        }),
        "chi" => Some(Language {
            english_name: "Chinese",
            two_letter_code: Some("zh"),
        }),
        "chk" => Some(Language {
            english_name: "Chuukese",
            two_letter_code: None,
        }),
        "chm" => Some(Language {
            english_name: "Mari",
            two_letter_code: None,
        }),
        "chn" => Some(Language {
            english_name: "Chinook jargon",
            two_letter_code: None,
        }),
        "cho" => Some(Language {
            english_name: "Choctaw",
            two_letter_code: None,
        }),
        "chp" => Some(Language {
            english_name: "Chipewyan",
            two_letter_code: None,
        }),
        "chr" => Some(Language {
            english_name: "Cherokee",
            two_letter_code: None,
        }),
        "chu" => Some(Language {
            english_name: "Church Slavic",
            two_letter_code: Some("cu"),
        }),
        "chv" => Some(Language {
            english_name: "Chuvash",
            two_letter_code: Some("cv"),
        }),
        "chy" => Some(Language {
            english_name: "Cheyenne",
            two_letter_code: None,
        }),
        "cmc" => Some(Language {
            english_name: "Chamic languages",
            two_letter_code: None,
        }),
        "cnr" => Some(Language {
            english_name: "Montenegrin",
            two_letter_code: None,
        }),
        "cop" => Some(Language {
            english_name: "Coptic",
            two_letter_code: None,
        }),
        "cor" => Some(Language {
            english_name: "Cornish",
            two_letter_code: Some("kw"),
        }),
        "cos" => Some(Language {
            english_name: "Corsican",
            two_letter_code: Some("co"),
        }),
        "cpe" => Some(Language {
            english_name: "Creoles and pidgins, English based",
            two_letter_code: None,
        }),
        "cpf" => Some(Language {
            english_name: "Creoles and pidgins, French-based",
            two_letter_code: None,
        }),
        "cpp" => Some(Language {
            english_name: "Creoles and pidgins, Portuguese-based",
            two_letter_code: None,
        }),
        "cre" => Some(Language {
            english_name: "Cree",
            two_letter_code: Some("cr"),
        }),
        "crh" => Some(Language {
            english_name: "Crimean Tatar",
            two_letter_code: None,
        }),
        "crp" => Some(Language {
            english_name: "Creoles and pidgins",
            two_letter_code: None,
        }),
        "csb" => Some(Language {
            english_name: "Kashubian",
            two_letter_code: None,
        }),
        "cus" => Some(Language {
            english_name: "Cushitic languages",
            two_letter_code: None,
        }),
        "cze" => Some(Language {
            english_name: "Czech",
            two_letter_code: Some("cs"),
        }),
        "dak" => Some(Language {
            english_name: "Dakota",
            two_letter_code: None,
        }),
        "dan" => Some(Language {
            english_name: "Danish",
            two_letter_code: Some("da"),
        }),
        "dar" => Some(Language {
            english_name: "Dargwa",
            two_letter_code: None,
        }),
        "day" => Some(Language {
            english_name: "Land Dayak languages",
            two_letter_code: None,
        }),
        "del" => Some(Language {
            english_name: "Delaware",
            two_letter_code: None,
        }),
        "den" => Some(Language {
            english_name: "Slave (Athapascan)",
            two_letter_code: None,
        }),
        "dgr" => Some(Language {
            english_name: "Tlicho",
            two_letter_code: None,
        }),
        "din" => Some(Language {
            english_name: "Dinka",
            two_letter_code: None,
        }),
        "div" => Some(Language {
            english_name: "Divehi",
            two_letter_code: Some("dv"),
        }),
        "doi" => Some(Language {
            english_name: "Dogri",
            two_letter_code: None,
        }),
        "dra" => Some(Language {
            english_name: "Dravidian languages",
            two_letter_code: None,
        }),
        "dsb" => Some(Language {
            english_name: "Lower Sorbian",
            two_letter_code: None,
        }),
        "dua" => Some(Language {
            english_name: "Duala",
            two_letter_code: None,
        }),
        "dum" => Some(Language {
            english_name: "Dutch, Middle (ca.1050-1350)",
            two_letter_code: None,
        }),
        "dut" => Some(Language {
            english_name: "Dutch",
            two_letter_code: Some("nl"),
        }),
        "dyu" => Some(Language {
            english_name: "Dyula",
            two_letter_code: None,
        }),
        "dzo" => Some(Language {
            english_name: "Dzongkha",
            two_letter_code: Some("dz"),
        }),
        "efi" => Some(Language {
            english_name: "Efik",
            two_letter_code: None,
        }),
        "egy" => Some(Language {
            english_name: "Egyptian (Ancient)",
            two_letter_code: None,
        }),
        "eka" => Some(Language {
            english_name: "Ekajuk",
            two_letter_code: None,
        }),
        "elx" => Some(Language {
            english_name: "Elamite",
            two_letter_code: None,
        }),
        "eng" => Some(Language {
            english_name: "English",
            two_letter_code: Some("en"),
        }),
        "enm" => Some(Language {
            english_name: "English, Middle (1100-1500)",
            two_letter_code: None,
        }),
        "epo" => Some(Language {
            english_name: "Esperanto",
            two_letter_code: Some("eo"),
        }),
        "est" => Some(Language {
            english_name: "Estonian",
            two_letter_code: Some("et"),
        }),
        "ewe" => Some(Language {
            english_name: "Ewe",
            two_letter_code: Some("ee"),
        }),
        "ewo" => Some(Language {
            english_name: "Ewondo",
            two_letter_code: None,
        }),
        "fan" => Some(Language {
            english_name: "Fang",
            two_letter_code: None,
        }),
        "fao" => Some(Language {
            english_name: "Faroese",
            two_letter_code: Some("fo"),
        }),
        "fat" => Some(Language {
            english_name: "Fanti",
            two_letter_code: None,
        }),
        "fij" => Some(Language {
            english_name: "Fijian",
            two_letter_code: Some("fj"),
        }),
        "fil" => Some(Language {
            english_name: "Filipino",
            two_letter_code: None,
        }),
        "fin" => Some(Language {
            english_name: "Finnish",
            two_letter_code: Some("fi"),
        }),
        "fiu" => Some(Language {
            english_name: "Finno-Ugrian languages",
            two_letter_code: None,
        }),
        "fon" => Some(Language {
            english_name: "Fon",
            two_letter_code: None,
        }),
        "fre" => Some(Language {
            english_name: "French",
            two_letter_code: Some("fr"),
        }),
        "frm" => Some(Language {
            english_name: "French, Middle (ca.1400-1600)",
            two_letter_code: None,
        }),
        "fro" => Some(Language {
            english_name: "French, Old (842-ca.1400)",
            two_letter_code: None,
        }),
        "frr" => Some(Language {
            english_name: "Northern Frisian",
            two_letter_code: None,
        }),
        "frs" => Some(Language {
            english_name: "Eastern Frisian",
            two_letter_code: None,
        }),
        "fry" => Some(Language {
            english_name: "Western Frisian",
            two_letter_code: Some("fy"),
        }),
        "ful" => Some(Language {
            english_name: "Fulah",
            two_letter_code: Some("ff"),
        }),
        "fur" => Some(Language {
            english_name: "Friulian",
            two_letter_code: None,
        }),
        "gaa" => Some(Language {
            english_name: "Ga",
            two_letter_code: None,
        }),
        "gay" => Some(Language {
            english_name: "Gayo",
            two_letter_code: None,
        }),
        "gba" => Some(Language {
            english_name: "Gbaya",
            two_letter_code: None,
        }),
        "gem" => Some(Language {
            english_name: "Germanic languages",
            two_letter_code: None,
        }),
        "geo" => Some(Language {
            english_name: "Georgian",
            two_letter_code: Some("ka"),
        }),
        "ger" => Some(Language {
            english_name: "German",
            two_letter_code: Some("de"),
        }),
        "gez" => Some(Language {
            english_name: "Geez",
            two_letter_code: None,
        }),
        "gil" => Some(Language {
            english_name: "Gilbertese",
            two_letter_code: None,
        }),
        "gla" => Some(Language {
            english_name: "Gaelic",
            two_letter_code: Some("gd"),
        }),
        "gle" => Some(Language {
            english_name: "Irish",
            two_letter_code: Some("ga"),
        }),
        "glg" => Some(Language {
            english_name: "Galician",
            two_letter_code: Some("gl"),
        }),
        "glv" => Some(Language {
            english_name: "Manx",
            two_letter_code: Some("gv"),
        }),
        "gmh" => Some(Language {
            english_name: "German, Middle High (ca.1050-1500)",
            two_letter_code: None,
        }),
        "goh" => Some(Language {
            english_name: "German, Old High (ca.750-1050)",
            two_letter_code: None,
        }),
        "gon" => Some(Language {
            english_name: "Gondi",
            two_letter_code: None,
        }),
        "gor" => Some(Language {
            english_name: "Gorontalo",
            two_letter_code: None,
        }),
        "got" => Some(Language {
            english_name: "Gothic",
            two_letter_code: None,
        }),
        "grb" => Some(Language {
            english_name: "Grebo",
            two_letter_code: None,
        }),
        "grc" => Some(Language {
            english_name: "Greek, Ancient (to 1453)",
            two_letter_code: None,
        }),
        "gre" => Some(Language {
            english_name: "Greek, Modern (1453-)",
            two_letter_code: Some("el"),
        }),
        "grn" => Some(Language {
            english_name: "Guarani",
            two_letter_code: Some("gn"),
        }),
        "gsw" => Some(Language {
            english_name: "Swiss German",
            two_letter_code: None,
        }),
        "guj" => Some(Language {
            english_name: "Gujarati",
            two_letter_code: Some("gu"),
        }),
        "gwi" => Some(Language {
            english_name: "Gwich'in",
            two_letter_code: None,
        }),
        "hai" => Some(Language {
            english_name: "Haida",
            two_letter_code: None,
        }),
        "hat" => Some(Language {
            english_name: "Haitian",
            two_letter_code: Some("ht"),
        }),
        "hau" => Some(Language {
            english_name: "Hausa",
            two_letter_code: Some("ha"),
        }),
        "haw" => Some(Language {
            english_name: "Hawaiian",
            two_letter_code: None,
        }),
        "heb" => Some(Language {
            english_name: "Hebrew",
            two_letter_code: Some("he"),
        }),
        "her" => Some(Language {
            english_name: "Herero",
            two_letter_code: Some("hz"),
        }),
        "hil" => Some(Language {
            english_name: "Hiligaynon",
            two_letter_code: None,
        }),
        "him" => Some(Language {
            english_name: "Himachali languages",
            two_letter_code: None,
        }),
        "hin" => Some(Language {
            english_name: "Hindi",
            two_letter_code: Some("hi"),
        }),
        "hit" => Some(Language {
            english_name: "Hittite",
            two_letter_code: None,
        }),
        "hmn" => Some(Language {
            english_name: "Hmong",
            two_letter_code: None,
        }),
        "hmo" => Some(Language {
            english_name: "Hiri Motu",
            two_letter_code: Some("ho"),
        }),
        "hrv" => Some(Language {
            english_name: "Croatian",
            two_letter_code: Some("hr"),
        }),
        "hsb" => Some(Language {
            english_name: "Upper Sorbian",
            two_letter_code: None,
        }),
        "hun" => Some(Language {
            english_name: "Hungarian",
            two_letter_code: Some("hu"),
        }),
        "hup" => Some(Language {
            english_name: "Hupa",
            two_letter_code: None,
        }),
        "iba" => Some(Language {
            english_name: "Iban",
            two_letter_code: None,
        }),
        "ibo" => Some(Language {
            english_name: "Igbo",
            two_letter_code: Some("ig"),
        }),
        "ice" => Some(Language {
            english_name: "Icelandic",
            two_letter_code: Some("is"),
        }),
        "ido" => Some(Language {
            english_name: "Ido",
            two_letter_code: Some("io"),
        }),
        "iii" => Some(Language {
            english_name: "Sichuan Yi",
            two_letter_code: Some("ii"),
        }),
        "ijo" => Some(Language {
            english_name: "Ijo languages",
            two_letter_code: None,
        }),
        "iku" => Some(Language {
            english_name: "Inuktitut",
            two_letter_code: Some("iu"),
        }),
        "ile" => Some(Language {
            english_name: "Interlingue",
            two_letter_code: Some("ie"),
        }),
        "ilo" => Some(Language {
            english_name: "Iloko",
            two_letter_code: None,
        }),
        "ina" => Some(Language {
            english_name: "Interlingua (International Auxiliary Language Association)",
            two_letter_code: Some("ia"),
        }),
        "inc" => Some(Language {
            english_name: "Indic languages",
            two_letter_code: None,
        }),
        "ind" => Some(Language {
            english_name: "Indonesian",
            two_letter_code: Some("id"),
        }),
        "ine" => Some(Language {
            english_name: "Indo-European languages",
            two_letter_code: None,
        }),
        "inh" => Some(Language {
            english_name: "Ingush",
            two_letter_code: None,
        }),
        "ipk" => Some(Language {
            english_name: "Inupiaq",
            two_letter_code: Some("ik"),
        }),
        "ira" => Some(Language {
            english_name: "Iranian languages",
            two_letter_code: None,
        }),
        "iro" => Some(Language {
            english_name: "Iroquoian languages",
            two_letter_code: None,
        }),
        "ita" => Some(Language {
            english_name: "Italian",
            two_letter_code: Some("it"),
        }),
        "jav" => Some(Language {
            english_name: "Javanese",
            two_letter_code: Some("jv"),
        }),
        "jbo" => Some(Language {
            english_name: "Lojban",
            two_letter_code: None,
        }),
        "jpn" => Some(Language {
            english_name: "Japanese",
            two_letter_code: Some("ja"),
        }),
        "jpr" => Some(Language {
            english_name: "Judeo-Persian",
            two_letter_code: None,
        }),
        "jrb" => Some(Language {
            english_name: "Judeo-Arabic",
            two_letter_code: None,
        }),
        "kaa" => Some(Language {
            english_name: "Kara-Kalpak",
            two_letter_code: None,
        }),
        "kab" => Some(Language {
            english_name: "Kabyle",
            two_letter_code: None,
        }),
        "kac" => Some(Language {
            english_name: "Kachin",
            two_letter_code: None,
        }),
        "kal" => Some(Language {
            english_name: "Kalaallisut",
            two_letter_code: Some("kl"),
        }),
        "kam" => Some(Language {
            english_name: "Kamba",
            two_letter_code: None,
        }),
        "kan" => Some(Language {
            english_name: "Kannada",
            two_letter_code: Some("kn"),
        }),
        "kar" => Some(Language {
            english_name: "Karen languages",
            two_letter_code: None,
        }),
        "kas" => Some(Language {
            english_name: "Kashmiri",
            two_letter_code: Some("ks"),
        }),
        "kau" => Some(Language {
            english_name: "Kanuri",
            two_letter_code: Some("kr"),
        }),
        "kaw" => Some(Language {
            english_name: "Kawi",
            two_letter_code: None,
        }),
        "kaz" => Some(Language {
            english_name: "Kazakh",
            two_letter_code: Some("kk"),
        }),
        "kbd" => Some(Language {
            english_name: "Kabardian",
            two_letter_code: None,
        }),
        "kha" => Some(Language {
            english_name: "Khasi",
            two_letter_code: None,
        }),
        "khi" => Some(Language {
            english_name: "Khoisan languages",
            two_letter_code: None,
        }),
        "khm" => Some(Language {
            english_name: "Central Khmer",
            two_letter_code: Some("km"),
        }),
        "kho" => Some(Language {
            english_name: "Khotanese",
            two_letter_code: None,
        }),
        "kik" => Some(Language {
            english_name: "Kikuyu",
            two_letter_code: Some("ki"),
        }),
        "kin" => Some(Language {
            english_name: "Kinyarwanda",
            two_letter_code: Some("rw"),
        }),
        "kir" => Some(Language {
            english_name: "Kirghiz",
            two_letter_code: Some("ky"),
        }),
        "kmb" => Some(Language {
            english_name: "Kimbundu",
            two_letter_code: None,
        }),
        "kok" => Some(Language {
            english_name: "Konkani",
            two_letter_code: None,
        }),
        "kom" => Some(Language {
            english_name: "Komi",
            two_letter_code: Some("kv"),
        }),
        "kon" => Some(Language {
            english_name: "Kongo",
            two_letter_code: Some("kg"),
        }),
        "kor" => Some(Language {
            english_name: "Korean",
            two_letter_code: Some("ko"),
        }),
        "kos" => Some(Language {
            english_name: "Kosraean",
            two_letter_code: None,
        }),
        "kpe" => Some(Language {
            english_name: "Kpelle",
            two_letter_code: None,
        }),
        "krc" => Some(Language {
            english_name: "Karachay-Balkar",
            two_letter_code: None,
        }),
        "krl" => Some(Language {
            english_name: "Karelian",
            two_letter_code: None,
        }),
        "kro" => Some(Language {
            english_name: "Kru languages",
            two_letter_code: None,
        }),
        "kru" => Some(Language {
            english_name: "Kurukh",
            two_letter_code: None,
        }),
        "kua" => Some(Language {
            english_name: "Kuanyama",
            two_letter_code: Some("kj"),
        }),
        "kum" => Some(Language {
            english_name: "Kumyk",
            two_letter_code: None,
        }),
        "kur" => Some(Language {
            english_name: "Kurdish",
            two_letter_code: Some("ku"),
        }),
        "kut" => Some(Language {
            english_name: "Kutenai",
            two_letter_code: None,
        }),
        "lad" => Some(Language {
            english_name: "Ladino",
            two_letter_code: None,
        }),
        "lah" => Some(Language {
            english_name: "Lahnda",
            two_letter_code: None,
        }),
        "lam" => Some(Language {
            english_name: "Lamba",
            two_letter_code: None,
        }),
        "lao" => Some(Language {
            english_name: "Lao",
            two_letter_code: Some("lo"),
        }),
        "lat" => Some(Language {
            english_name: "Latin",
            two_letter_code: Some("la"),
        }),
        "lav" => Some(Language {
            english_name: "Latvian",
            two_letter_code: Some("lv"),
        }),
        "lez" => Some(Language {
            english_name: "Lezghian",
            two_letter_code: None,
        }),
        "lim" => Some(Language {
            english_name: "Limburgan",
            two_letter_code: Some("li"),
        }),
        "lin" => Some(Language {
            english_name: "Lingala",
            two_letter_code: Some("ln"),
        }),
        "lit" => Some(Language {
            english_name: "Lithuanian",
            two_letter_code: Some("lt"),
        }),
        "lol" => Some(Language {
            english_name: "Mongo",
            two_letter_code: None,
        }),
        "loz" => Some(Language {
            english_name: "Lozi",
            two_letter_code: None,
        }),
        "ltz" => Some(Language {
            english_name: "Luxembourgish",
            two_letter_code: Some("lb"),
        }),
        "lua" => Some(Language {
            english_name: "Luba-Lulua",
            two_letter_code: None,
        }),
        "lub" => Some(Language {
            english_name: "Luba-Katanga",
            two_letter_code: Some("lu"),
        }),
        "lug" => Some(Language {
            english_name: "Ganda",
            two_letter_code: Some("lg"),
        }),
        "lui" => Some(Language {
            english_name: "Luiseno",
            two_letter_code: None,
        }),
        "lun" => Some(Language {
            english_name: "Lunda",
            two_letter_code: None,
        }),
        "luo" => Some(Language {
            english_name: "Luo (Kenya and Tanzania)",
            two_letter_code: None,
        }),
        "lus" => Some(Language {
            english_name: "Lushai",
            two_letter_code: None,
        }),
        "mac" => Some(Language {
            english_name: "Macedonian",
            two_letter_code: Some("mk"),
        }),
        "mad" => Some(Language {
            english_name: "Madurese",
            two_letter_code: None,
        }),
        "mag" => Some(Language {
            english_name: "Magahi",
            two_letter_code: None,
        }),
        "mah" => Some(Language {
            english_name: "Marshallese",
            two_letter_code: Some("mh"),
        }),
        "mai" => Some(Language {
            english_name: "Maithili",
            two_letter_code: None,
        }),
        "mak" => Some(Language {
            english_name: "Makasar",
            two_letter_code: None,
        }),
        "mal" => Some(Language {
            english_name: "Malayalam",
            two_letter_code: Some("ml"),
        }),
        "man" => Some(Language {
            english_name: "Mandingo",
            two_letter_code: None,
        }),
        "mao" => Some(Language {
            english_name: "Maori",
            two_letter_code: Some("mi"),
        }),
        "map" => Some(Language {
            english_name: "Austronesian languages",
            two_letter_code: None,
        }),
        "mar" => Some(Language {
            english_name: "Marathi",
            two_letter_code: Some("mr"),
        }),
        "mas" => Some(Language {
            english_name: "Masai",
            two_letter_code: None,
        }),
        "may" => Some(Language {
            english_name: "Malay",
            two_letter_code: Some("ms"),
        }),
        "mdf" => Some(Language {
            english_name: "Moksha",
            two_letter_code: None,
        }),
        "mdr" => Some(Language {
            english_name: "Mandar",
            two_letter_code: None,
        }),
        "men" => Some(Language {
            english_name: "Mende",
            two_letter_code: None,
        }),
        "mga" => Some(Language {
            english_name: "Irish, Middle (900-1200)",
            two_letter_code: None,
        }),
        "mic" => Some(Language {
            english_name: "Mi'kmaq",
            two_letter_code: None,
        }),
        "min" => Some(Language {
            english_name: "Minangkabau",
            two_letter_code: None,
        }),
        "mis" => Some(Language {
            english_name: "Uncoded languages",
            two_letter_code: None,
        }),
        "mkh" => Some(Language {
            english_name: "Mon-Khmer languages",
            two_letter_code: None,
        }),
        "mlg" => Some(Language {
            english_name: "Malagasy",
            two_letter_code: Some("mg"),
        }),
        "mlt" => Some(Language {
            english_name: "Maltese",
            two_letter_code: Some("mt"),
        }),
        "mnc" => Some(Language {
            english_name: "Manchu",
            two_letter_code: None,
        }),
        "mni" => Some(Language {
            english_name: "Manipuri",
            two_letter_code: None,
        }),
        "mno" => Some(Language {
            english_name: "Manobo languages",
            two_letter_code: None,
        }),
        "moh" => Some(Language {
            english_name: "Mohawk",
            two_letter_code: None,
        }),
        "mon" => Some(Language {
            english_name: "Mongolian",
            two_letter_code: Some("mn"),
        }),
        "mos" => Some(Language {
            english_name: "Mossi",
            two_letter_code: None,
        }),
        "mul" => Some(Language {
            english_name: "Multiple languages",
            two_letter_code: None,
        }),
        "mun" => Some(Language {
            english_name: "Munda languages",
            two_letter_code: None,
        }),
        "mus" => Some(Language {
            english_name: "Creek",
            two_letter_code: None,
        }),
        "mwl" => Some(Language {
            english_name: "Mirandese",
            two_letter_code: None,
        }),
        "mwr" => Some(Language {
            english_name: "Marwari",
            two_letter_code: None,
        }),
        "myn" => Some(Language {
            english_name: "Mayan languages",
            two_letter_code: None,
        }),
        "myv" => Some(Language {
            english_name: "Erzya",
            two_letter_code: None,
        }),
        "nah" => Some(Language {
            english_name: "Nahuatl languages",
            two_letter_code: None,
        }),
        "nai" => Some(Language {
            english_name: "North American Indian languages",
            two_letter_code: None,
        }),
        "nap" => Some(Language {
            english_name: "Neapolitan",
            two_letter_code: None,
        }),
        "nau" => Some(Language {
            english_name: "Nauru",
            two_letter_code: Some("na"),
        }),
        "nav" => Some(Language {
            english_name: "Navajo",
            two_letter_code: Some("nv"),
        }),
        "nbl" => Some(Language {
            english_name: "Ndebele, South",
            two_letter_code: Some("nr"),
        }),
        "nde" => Some(Language {
            english_name: "Ndebele, North",
            two_letter_code: Some("nd"),
        }),
        "ndo" => Some(Language {
            english_name: "Ndonga",
            two_letter_code: Some("ng"),
        }),
        "nds" => Some(Language {
            english_name: "Low German",
            two_letter_code: None,
        }),
        "nep" => Some(Language {
            english_name: "Nepali",
            two_letter_code: Some("ne"),
        }),
        "new" => Some(Language {
            english_name: "Nepal Bhasa",
            two_letter_code: None,
        }),
        "nia" => Some(Language {
            english_name: "Nias",
            two_letter_code: None,
        }),
        "nic" => Some(Language {
            english_name: "Niger-Kordofanian languages",
            two_letter_code: None,
        }),
        "niu" => Some(Language {
            english_name: "Niuean",
            two_letter_code: None,
        }),
        "nno" => Some(Language {
            english_name: "Norwegian Nynorsk",
            two_letter_code: Some("nn"),
        }),
        "nob" => Some(Language {
            english_name: "BokmÃ¥l, Norwegian",
            two_letter_code: Some("nb"),
        }),
        "nog" => Some(Language {
            english_name: "Nogai",
            two_letter_code: None,
        }),
        "non" => Some(Language {
            english_name: "Norse, Old",
            two_letter_code: None,
        }),
        "nor" => Some(Language {
            english_name: "Norwegian",
            two_letter_code: Some("no"),
        }),
        "nqo" => Some(Language {
            english_name: "N'Ko",
            two_letter_code: None,
        }),
        "nso" => Some(Language {
            english_name: "Pedi",
            two_letter_code: None,
        }),
        "nub" => Some(Language {
            english_name: "Nubian languages",
            two_letter_code: None,
        }),
        "nwc" => Some(Language {
            english_name: "Classical Newari",
            two_letter_code: None,
        }),
        "nya" => Some(Language {
            english_name: "Chichewa",
            two_letter_code: Some("ny"),
        }),
        "nym" => Some(Language {
            english_name: "Nyamwezi",
            two_letter_code: None,
        }),
        "nyn" => Some(Language {
            english_name: "Nyankole",
            two_letter_code: None,
        }),
        "nyo" => Some(Language {
            english_name: "Nyoro",
            two_letter_code: None,
        }),
        "nzi" => Some(Language {
            english_name: "Nzima",
            two_letter_code: None,
        }),
        "oci" => Some(Language {
            english_name: "Occitan (post 1500)",
            two_letter_code: Some("oc"),
        }),
        "oji" => Some(Language {
            english_name: "Ojibwa",
            two_letter_code: Some("oj"),
        }),
        "ori" => Some(Language {
            english_name: "Oriya",
            two_letter_code: Some("or"),
        }),
        "orm" => Some(Language {
            english_name: "Oromo",
            two_letter_code: Some("om"),
        }),
        "osa" => Some(Language {
            english_name: "Osage",
            two_letter_code: None,
        }),
        "oss" => Some(Language {
            english_name: "Ossetian",
            two_letter_code: Some("os"),
        }),
        "ota" => Some(Language {
            english_name: "Turkish, Ottoman (1500-1928)",
            two_letter_code: None,
        }),
        "oto" => Some(Language {
            english_name: "Otomian languages",
            two_letter_code: None,
        }),
        "paa" => Some(Language {
            english_name: "Papuan languages",
            two_letter_code: None,
        }),
        "pag" => Some(Language {
            english_name: "Pangasinan",
            two_letter_code: None,
        }),
        "pal" => Some(Language {
            english_name: "Pahlavi",
            two_letter_code: None,
        }),
        "pam" => Some(Language {
            english_name: "Pampanga",
            two_letter_code: None,
        }),
        "pan" => Some(Language {
            english_name: "Panjabi",
            two_letter_code: Some("pa"),
        }),
        "pap" => Some(Language {
            english_name: "Papiamento",
            two_letter_code: None,
        }),
        "pau" => Some(Language {
            english_name: "Palauan",
            two_letter_code: None,
        }),
        "peo" => Some(Language {
            english_name: "Persian, Old (ca.600-400 B.C.)",
            two_letter_code: None,
        }),
        "per" => Some(Language {
            english_name: "Persian",
            two_letter_code: Some("fa"),
        }),
        "phi" => Some(Language {
            english_name: "Philippine languages",
            two_letter_code: None,
        }),
        "phn" => Some(Language {
            english_name: "Phoenician",
            two_letter_code: None,
        }),
        "pli" => Some(Language {
            english_name: "Pali",
            two_letter_code: Some("pi"),
        }),
        "pol" => Some(Language {
            english_name: "Polish",
            two_letter_code: Some("pl"),
        }),
        "pon" => Some(Language {
            english_name: "Pohnpeian",
            two_letter_code: None,
        }),
        "por" => Some(Language {
            english_name: "Portuguese",
            two_letter_code: Some("pt"),
        }),
        "pra" => Some(Language {
            english_name: "Prakrit languages",
            two_letter_code: None,
        }),
        "pro" => Some(Language {
            english_name: "ProvenÃ§al, Old (to 1500)",
            two_letter_code: None,
        }),
        "pus" => Some(Language {
            english_name: "Pushto",
            two_letter_code: Some("ps"),
        }),
        "que" => Some(Language {
            english_name: "Quechua",
            two_letter_code: Some("qu"),
        }),
        "raj" => Some(Language {
            english_name: "Rajasthani",
            two_letter_code: None,
        }),
        "rap" => Some(Language {
            english_name: "Rapanui",
            two_letter_code: None,
        }),
        "rar" => Some(Language {
            english_name: "Rarotongan",
            two_letter_code: None,
        }),
        "roa" => Some(Language {
            english_name: "Romance languages",
            two_letter_code: None,
        }),
        "roh" => Some(Language {
            english_name: "Romansh",
            two_letter_code: Some("rm"),
        }),
        "rom" => Some(Language {
            english_name: "Romany",
            two_letter_code: None,
        }),
        "rum" => Some(Language {
            english_name: "Romanian",
            two_letter_code: Some("ro"),
        }),
        "run" => Some(Language {
            english_name: "Rundi",
            two_letter_code: Some("rn"),
        }),
        "rup" => Some(Language {
            english_name: "Aromanian",
            two_letter_code: None,
        }),
        "rus" => Some(Language {
            english_name: "Russian",
            two_letter_code: Some("ru"),
        }),
        "sad" => Some(Language {
            english_name: "Sandawe",
            two_letter_code: None,
        }),
        "sag" => Some(Language {
            english_name: "Sango",
            two_letter_code: Some("sg"),
        }),
        "sah" => Some(Language {
            english_name: "Yakut",
            two_letter_code: None,
        }),
        "sai" => Some(Language {
            english_name: "South American Indian languages",
            two_letter_code: None,
        }),
        "sal" => Some(Language {
            english_name: "Salishan languages",
            two_letter_code: None,
        }),
        "sam" => Some(Language {
            english_name: "Samaritan Aramaic",
            two_letter_code: None,
        }),
        "san" => Some(Language {
            english_name: "Sanskrit",
            two_letter_code: Some("sa"),
        }),
        "sas" => Some(Language {
            english_name: "Sasak",
            two_letter_code: None,
        }),
        "sat" => Some(Language {
            english_name: "Santali",
            two_letter_code: None,
        }),
        "scn" => Some(Language {
            english_name: "Sicilian",
            two_letter_code: None,
        }),
        "sco" => Some(Language {
            english_name: "Scots",
            two_letter_code: None,
        }),
        "sel" => Some(Language {
            english_name: "Selkup",
            two_letter_code: None,
        }),
        "sem" => Some(Language {
            english_name: "Semitic languages",
            two_letter_code: None,
        }),
        "sga" => Some(Language {
            english_name: "Irish, Old (to 900)",
            two_letter_code: None,
        }),
        "sgn" => Some(Language {
            english_name: "Sign Languages",
            two_letter_code: None,
        }),
        "shn" => Some(Language {
            english_name: "Shan",
            two_letter_code: None,
        }),
        "sid" => Some(Language {
            english_name: "Sidamo",
            two_letter_code: None,
        }),
        "sin" => Some(Language {
            english_name: "Sinhala",
            two_letter_code: Some("si"),
        }),
        "sio" => Some(Language {
            english_name: "Siouan languages",
            two_letter_code: None,
        }),
        "sit" => Some(Language {
            english_name: "Sino-Tibetan languages",
            two_letter_code: None,
        }),
        "sla" => Some(Language {
            english_name: "Slavic languages",
            two_letter_code: None,
        }),
        "slo" => Some(Language {
            english_name: "Slovak",
            two_letter_code: Some("sk"),
        }),
        "slv" => Some(Language {
            english_name: "Slovenian",
            two_letter_code: Some("sl"),
        }),
        "sma" => Some(Language {
            english_name: "Southern Sami",
            two_letter_code: None,
        }),
        "sme" => Some(Language {
            english_name: "Northern Sami",
            two_letter_code: Some("se"),
        }),
        "smi" => Some(Language {
            english_name: "Sami languages",
            two_letter_code: None,
        }),
        "smj" => Some(Language {
            english_name: "Lule Sami",
            two_letter_code: None,
        }),
        "smn" => Some(Language {
            english_name: "Inari Sami",
            two_letter_code: None,
        }),
        "smo" => Some(Language {
            english_name: "Samoan",
            two_letter_code: Some("sm"),
        }),
        "sms" => Some(Language {
            english_name: "Skolt Sami",
            two_letter_code: None,
        }),
        "sna" => Some(Language {
            english_name: "Shona",
            two_letter_code: Some("sn"),
        }),
        "snd" => Some(Language {
            english_name: "Sindhi",
            two_letter_code: Some("sd"),
        }),
        "snk" => Some(Language {
            english_name: "Soninke",
            two_letter_code: None,
        }),
        "sog" => Some(Language {
            english_name: "Sogdian",
            two_letter_code: None,
        }),
        "som" => Some(Language {
            english_name: "Somali",
            two_letter_code: Some("so"),
        }),
        "son" => Some(Language {
            english_name: "Songhai languages",
            two_letter_code: None,
        }),
        "sot" => Some(Language {
            english_name: "Sotho, Southern",
            two_letter_code: Some("st"),
        }),
        "spa" => Some(Language {
            english_name: "Spanish",
            two_letter_code: Some("es"),
        }),
        "srd" => Some(Language {
            english_name: "Sardinian",
            two_letter_code: Some("sc"),
        }),
        "srn" => Some(Language {
            english_name: "Sranan Tongo",
            two_letter_code: None,
        }),
        "srp" => Some(Language {
            english_name: "Serbian",
            two_letter_code: Some("sr"),
        }),
        "srr" => Some(Language {
            english_name: "Serer",
            two_letter_code: None,
        }),
        "ssa" => Some(Language {
            english_name: "Nilo-Saharan languages",
            two_letter_code: None,
        }),
        "ssw" => Some(Language {
            english_name: "Swati",
            two_letter_code: Some("ss"),
        }),
        "suk" => Some(Language {
            english_name: "Sukuma",
            two_letter_code: None,
        }),
        "sun" => Some(Language {
            english_name: "Sundanese",
            two_letter_code: Some("su"),
        }),
        "sus" => Some(Language {
            english_name: "Susu",
            two_letter_code: None,
        }),
        "sux" => Some(Language {
            english_name: "Sumerian",
            two_letter_code: None,
        }),
        "swa" => Some(Language {
            english_name: "Swahili",
            two_letter_code: Some("sw"),
        }),
        "swe" => Some(Language {
            english_name: "Swedish",
            two_letter_code: Some("sv"),
        }),
        "syc" => Some(Language {
            english_name: "Classical Syriac",
            two_letter_code: None,
        }),
        "syr" => Some(Language {
            english_name: "Syriac",
            two_letter_code: None,
        }),
        "tah" => Some(Language {
            english_name: "Tahitian",
            two_letter_code: Some("ty"),
        }),
        "tai" => Some(Language {
            english_name: "Tai languages",
            two_letter_code: None,
        }),
        "tam" => Some(Language {
            english_name: "Tamil",
            two_letter_code: Some("ta"),
        }),
        "tat" => Some(Language {
            english_name: "Tatar",
            two_letter_code: Some("tt"),
        }),
        "tel" => Some(Language {
            english_name: "Telugu",
            two_letter_code: Some("te"),
        }),
        "tem" => Some(Language {
            english_name: "Timne",
            two_letter_code: None,
        }),
        "ter" => Some(Language {
            english_name: "Tereno",
            two_letter_code: None,
        }),
        "tet" => Some(Language {
            english_name: "Tetum",
            two_letter_code: None,
        }),
        "tgk" => Some(Language {
            english_name: "Tajik",
            two_letter_code: Some("tg"),
        }),
        "tgl" => Some(Language {
            english_name: "Tagalog",
            two_letter_code: Some("tl"),
        }),
        "tha" => Some(Language {
            english_name: "Thai",
            two_letter_code: Some("th"),
        }),
        "tib" => Some(Language {
            english_name: "Tibetan",
            two_letter_code: Some("bo"),
        }),
        "tig" => Some(Language {
            english_name: "Tigre",
            two_letter_code: None,
        }),
        "tir" => Some(Language {
            english_name: "Tigrinya",
            two_letter_code: Some("ti"),
        }),
        "tiv" => Some(Language {
            english_name: "Tiv",
            two_letter_code: None,
        }),
        "tkl" => Some(Language {
            english_name: "Tokelau",
            two_letter_code: None,
        }),
        "tlh" => Some(Language {
            english_name: "Klingon",
            two_letter_code: None,
        }),
        "tli" => Some(Language {
            english_name: "Tlingit",
            two_letter_code: None,
        }),
        "tmh" => Some(Language {
            english_name: "Tamashek",
            two_letter_code: None,
        }),
        "tog" => Some(Language {
            english_name: "Tonga (Nyasa)",
            two_letter_code: None,
        }),
        "ton" => Some(Language {
            english_name: "Tonga (Tonga Islands)",
            two_letter_code: Some("to"),
        }),
        "tpi" => Some(Language {
            english_name: "Tok Pisin",
            two_letter_code: None,
        }),
        "tsi" => Some(Language {
            english_name: "Tsimshian",
            two_letter_code: None,
        }),
        "tsn" => Some(Language {
            english_name: "Tswana",
            two_letter_code: Some("tn"),
        }),
        "tso" => Some(Language {
            english_name: "Tsonga",
            two_letter_code: Some("ts"),
        }),
        "tuk" => Some(Language {
            english_name: "Turkmen",
            two_letter_code: Some("tk"),
        }),
        "tum" => Some(Language {
            english_name: "Tumbuka",
            two_letter_code: None,
        }),
        "tup" => Some(Language {
            english_name: "Tupi languages",
            two_letter_code: None,
        }),
        "tur" => Some(Language {
            english_name: "Turkish",
            two_letter_code: Some("tr"),
        }),
        "tut" => Some(Language {
            english_name: "Altaic languages",
            two_letter_code: None,
        }),
        "tvl" => Some(Language {
            english_name: "Tuvalu",
            two_letter_code: None,
        }),
        "twi" => Some(Language {
            english_name: "Twi",
            two_letter_code: Some("tw"),
        }),
        "tyv" => Some(Language {
            english_name: "Tuvinian",
            two_letter_code: None,
        }),
        "udm" => Some(Language {
            english_name: "Udmurt",
            two_letter_code: None,
        }),
        "uga" => Some(Language {
            english_name: "Ugaritic",
            two_letter_code: None,
        }),
        "uig" => Some(Language {
            english_name: "Uighur",
            two_letter_code: Some("ug"),
        }),
        "ukr" => Some(Language {
            english_name: "Ukrainian",
            two_letter_code: Some("uk"),
        }),
        "umb" => Some(Language {
            english_name: "Umbundu",
            two_letter_code: None,
        }),
        "und" => Some(Language {
            english_name: "Undetermined",
            two_letter_code: None,
        }),
        "urd" => Some(Language {
            english_name: "Urdu",
            two_letter_code: Some("ur"),
        }),
        "uzb" => Some(Language {
            english_name: "Uzbek",
            two_letter_code: Some("uz"),
        }),
        "vai" => Some(Language {
            english_name: "Vai",
            two_letter_code: None,
        }),
        "ven" => Some(Language {
            english_name: "Venda",
            two_letter_code: Some("ve"),
        }),
        "vie" => Some(Language {
            english_name: "Vietnamese",
            two_letter_code: Some("vi"),
        }),
        "vol" => Some(Language {
            english_name: "VolapÃ¼k",
            two_letter_code: Some("vo"),
        }),
        "vot" => Some(Language {
            english_name: "Votic",
            two_letter_code: None,
        }),
        "wak" => Some(Language {
            english_name: "Wakashan languages",
            two_letter_code: None,
        }),
        "wal" => Some(Language {
            english_name: "Wolaitta",
            two_letter_code: None,
        }),
        "war" => Some(Language {
            english_name: "Waray",
            two_letter_code: None,
        }),
        "was" => Some(Language {
            english_name: "Washo",
            two_letter_code: None,
        }),
        "wel" => Some(Language {
            english_name: "Welsh",
            two_letter_code: Some("cy"),
        }),
        "wen" => Some(Language {
            english_name: "Sorbian languages",
            two_letter_code: None,
        }),
        "wln" => Some(Language {
            english_name: "Walloon",
            two_letter_code: Some("wa"),
        }),
        "wol" => Some(Language {
            english_name: "Wolof",
            two_letter_code: Some("wo"),
        }),
        "xal" => Some(Language {
            english_name: "Kalmyk",
            two_letter_code: None,
        }),
        "xho" => Some(Language {
            english_name: "Xhosa",
            two_letter_code: Some("xh"),
        }),
        "yao" => Some(Language {
            english_name: "Yao",
            two_letter_code: None,
        }),
        "yap" => Some(Language {
            english_name: "Yapese",
            two_letter_code: None,
        }),
        "yid" => Some(Language {
            english_name: "Yiddish",
            two_letter_code: Some("yi"),
        }),
        "yor" => Some(Language {
            english_name: "Yoruba",
            two_letter_code: Some("yo"),
        }),
        "ypk" => Some(Language {
            english_name: "Yupik languages",
            two_letter_code: None,
        }),
        "zap" => Some(Language {
            english_name: "Zapotec",
            two_letter_code: None,
        }),
        "zbl" => Some(Language {
            english_name: "Blissymbols",
            two_letter_code: None,
        }),
        "zen" => Some(Language {
            english_name: "Zenaga",
            two_letter_code: None,
        }),
        "zgh" => Some(Language {
            english_name: "Standard Moroccan Tamazight",
            two_letter_code: None,
        }),
        "zha" => Some(Language {
            english_name: "Zhuang",
            two_letter_code: Some("za"),
        }),
        "znd" => Some(Language {
            english_name: "Zande languages",
            two_letter_code: None,
        }),
        "zul" => Some(Language {
            english_name: "Zulu",
            two_letter_code: Some("zu"),
        }),
        "zun" => Some(Language {
            english_name: "Zuni",
            two_letter_code: None,
        }),
        "zxx" => Some(Language {
            english_name: "No linguistic content",
            two_letter_code: None,
        }),
        "zza" => Some(Language {
            english_name: "Zaza",
            two_letter_code: None,
        }),
        _ => None,
    }
}
